@baseUrl = http://localhost:666/api/v2

### Read all users
GET {{baseUrl}}/users

### Create a new user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "username": "siwat",
  "email": "siwat@mail",
  "password": "test123"
}